# Generated by Django 6.0.3 on 2026-04-05 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue', to='resources.resource'),
        ),
    ]
