# Generated by Django 6.0.6 on 2026-06-09 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_catalogueprogress_topic_quizquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueprogress',
            name='catalogue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='catalogues.catalogue'),
        ),
    ]
