# Generated by Django 6.0.3 on 2026-04-07 02:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0003_alter_resource_file_alter_resource_file_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("resource_upload", "Resource Upload"),
                            ("resource_approved", "Resource Approved"),
                            ("bookmark_add", "Added Bookmark"),
                            ("bookmark_remove", "Removed Bookmark"),
                            ("review_create", "Created Review"),
                            ("review_update", "Updated Review"),
                            ("assessment_start", "Assessment Started"),
                            ("assessment_complete", "Assessment Completed"),
                            ("catalogue_complete", "Catalogue Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_actions",
                        to="resources.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_us_user_id_3bc625_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="activity_us_action__6a4bbe_idx",
                    ),
                ],
            },
        ),
    ]
