# Generated by Django 6.0.6 on 2026-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('resource_upload', 'Resource Upload'), ('resource_approved', 'Resource Approved'), ('bookmark_add', 'Added Bookmark'), ('bookmark_remove', 'Removed Bookmark'), ('assessment_start', 'Assessment Started'), ('assessment_complete', 'Assessment Completed'), ('catalogue_complete', 'Catalogue Completed')], max_length=50),
        ),
    ]
