# Generated by Django 6.0.3 on 2026-04-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded resource file",
                null=True,
                upload_to="resources/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="processing_error",
            field=models.TextField(
                blank=True, help_text="Error message if processing failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="raw_text",
            field=models.TextField(
                blank=True, help_text="Extracted text from file", null=True
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
