# Generated by Django 6.0.3 on 2026-04-07 02:30

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_resource_file_resource_processing_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded resource file",
                null=True,
                upload_to=resources.models.resource_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("doc", "DOC"),
                    ("docx", "DOCX"),
                    ("ppt", "PPT"),
                    ("pptx", "PPTX"),
                    ("txt", "Text"),
                    ("image", "Image"),
                    ("document", "Document"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
