# Generated by Django 6.0.3 on 2026-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_file_alter_resource_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, help_text='Last time processing was attempted', null=True),
        ),
    ]
