import { Brain, Layers3, Sparkles, Timer, Wand2, ShieldCheck } from "lucide-react";
import { motion } from "framer-motion";
import GlassCard from "./GlassCard";
import { Reveal, useMotionOK } from "./MotionPrimitives";

const features = [
  {
    icon: Sparkles,
    title: "Glassmorphism UI",
    desc: "Modern dark theme with frosted glass effects, smooth animations, and premium feel.",
  },
  {
    icon: Brain,
    title: "AI-powered catalogues",
    desc: "Upload files and get structured learning catalogues with summaries and quizzes automatically generated by LLaMA 3.1 70B.",
  },
  {
    icon: Wand2,
    title: "Auto-generated quizzes",
    desc: "Multiple-choice questions created from your content with instant grading and 5 points per correct answer.",
  },
  {
    icon: Layers3,
    title: "Topic-based learning",
    desc: "Study materials organized into catalogues with topics, each with content, summaries, and dedicated quizzes.",
  },
  {
    icon: Timer,
    title: "Guided study sessions",
    desc: "Progress through topics one at a time with completion tracking and percentage-based progress indicators.",
  },
  {
    icon: ShieldCheck,
    title: "Gamification system",
    desc: "Earn points from quizzes, maintain daily login streaks, and track your progress across all catalogues.",
  },
];

export default function LandingFeatures() {
  const motionOK = useMotionOK();

  return (
    <section id="features" className="relative pt-20 sm:pt-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <Reveal>
          <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div>
              <div className="text-sm text-tertiary font-semibold tracking-wide">
                Features
              </div>
              <h2 className="mt-2 text-3xl sm:text-4xl font-bold tracking-tight">
                Everything you need to study smarter
              </h2>
              <p className="mt-3 text-on-surface-variant max-w-2xl">
                AI-powered catalogues, automatic quizzes, progress tracking, and a
                beautiful glassmorphism interface.
              </p>
            </div>
          </div>
        </Reveal>

        <div className="mt-10 grid gap-4 sm:gap-6 md:grid-cols-2 lg:grid-cols-3">
          {features.map((f, idx) => (
            <Reveal key={f.title} delay={idx * 0.06}>
              <motion.div
                whileHover={motionOK ? { y: -6, scale: 1.01 } : {}}
                transition={{ duration: 0.25 }}
              >
                <GlassCard className="h-full p-6">
                  <div className="flex items-start gap-4">
                    <div className="h-12 w-12 rounded-2xl sm:bg-surface-container-high/40 sm:border border-outline-variant/20 flex items-center justify-center">
                      <f.icon className="h-5 w-5 text-tertiary" />
                    </div>
                    <div>
                      <div className="text-lg font-semibold tracking-tight">
                        {f.title}
                      </div>
                      <p className="mt-2 text-sm text-on-surface-variant">
                        {f.desc}
                      </p>
                    </div>
                  </div>
                  <div className="mt-6 h-[1px] bg-outline-variant/15" />
                </GlassCard>
              </motion.div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

